version: '2.2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka-1:
    image: confluentinc/cp-kafka:5.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_ADVERTISED_LISTENERS: HOST://127.0.0.1:9092,DOCKER://kafka-1:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    ports:
      - 127.0.0.1:9092:9092
  kafka-2:
    image: confluentinc/cp-kafka:5.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_ADVERTISED_LISTENERS: HOST://127.0.0.1:9093,DOCKER://kafka-2:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    ports:
      - 127.0.0.1:9093:9093
  kafka-3:
    image: confluentinc/cp-kafka:5.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_ADVERTISED_LISTENERS: HOST://127.0.0.1:9094,DOCKER://kafka-3:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    ports:
      - 127.0.0.1:9094:9094
